default:
  properties:
    parsys.finder.offset: 6

    proxy.enabled: false
    proxy.ip: 127.0.0.1
    proxy.port: 9000

    analytics.uri.prefix:  /b/ss
    analytics.call.timeout.ms:  30000

    webdriver.mobile: false
    webdriver.maximize: true
    webdriver.reusable: false
    webdriver.url: ''

    cookies.loadAutomatically: true

    modifiers.implicitTimeout: true
    timings.explicitTimeout: 10
    timings.implicitTimeout: 1
    timings.pollingInterval: 500

    webdriver.chrome.headless: false
    webdriver.chrome.acceptInsecureCerts: false
